const chapter5Data = [
    // --- DATABASE BASICS & DBMS ---
    { q: "An organized collection of data is called a:", options: ["Folder", "Database", "File", "Cabinet"], correct: 1 },
    { q: "What does DBMS allow you to do with data?", options: ["Store and retrieve", "Modify and delete", "Manage information", "All of these"], correct: 3 },
    { q: "Full form of DBMS is:", options: ["Data Base Management System", "Database Manual System", "Digital Base System", "None"], correct: 0 },
    { q: "Who built the Analytical Machine, the first programmable computer?", options: ["Charles Babbage", "Bill Gates", "Alan Turing", "Steve Jobs"], correct: 0 },
    { q: "A telephone address book is an example of a:", options: ["Spreadsheet", "Database", "Text file", "Application"], correct: 1 },
    { q: "Banks use databases to keep track of:", options: ["Customer balances", "Account transactions", "Deposits", "All of these"], correct: 3 },
    { q: "Manual databases on paper are prone to:", options: ["High speed", "Errors", "Security", "Flexibility"], correct: 1 },
    { q: "Databases allow multiple users to access data at:", options: ["Different times", "Once (simultaneously)", "Only on weekends", "Never"], correct: 1 },
    { q: "Plain text databases with fixed structures are called:", options: ["Relational", "Flat-file", "Multi-dimensional", "Network"], correct: 1 },
    { q: "Which database type uses related tables of information?", options: ["Flat-file", "Relational", "Linear", "Simple"], correct: 1 },
    { q: "What is the primary form of data storage in a database?", options: ["Queries", "Tables", "Forms", "Reports"], correct: 1 },
    { q: "The intersection of a row and a column is a:", options: ["Record", "Field", "Cell", "Value"], correct: 2 },
    { q: "Columns in a table are also known as:", options: ["Records", "Tuples", "Fields (Attributes)", "Sheets"], correct: 2 },
    { q: "Rows in a table are also known as:", options: ["Fields", "Records (Tuples)", "Cells", "Attributes"], correct: 1 },
    { q: "A request for specific information from a table is a:", options: ["Report", "Form", "Query", "Link"], correct: 2 },
    { q: "The condition specified in a query is called:", options: ["Filter", "Criteria", "Selection", "Logic"], correct: 1 },
    { q: "Which component provides a user-friendly interface for data entry?", options: ["Table", "Form", "Query", "Report"], correct: 1 },
    { q: "The formatted and printable result of a database is a:", options: ["Query", "Form", "Report", "Record"], correct: 2 },
    { q: "MS Access is a part of which software suite?", options: ["Adobe", "Microsoft Office", "Google", "Linux"], correct: 1 },
    { q: "Access uses which database engine?", options: ["Oracle", "Microsoft Jet Database Engine", "SQL Server", "MySQL"], correct: 1 },
    { q: "Which view is used to define the structure of a table?", options: ["Datasheet View", "Design View", "Print View", "SQL View"], correct: 1 },
    { q: "Which view is used for entering data into the table?", options: ["Design View", "Datasheet View", "Layout View", "Form View"], correct: 1 },
    { q: "Title bar in Access displays the name of the:", options: ["User", "Application and Database", "Computer", "ISP"], correct: 1 },
    { q: "Where can you find the Save, Undo, and Redo buttons?", options: ["Ribbon", "Status Bar", "Quick Access Toolbar", "Navigation Pane"], correct: 2 },
    { q: "The 'Ribbon' in Access contains:", options: ["File names", "Tabs and groups of commands", "Current record numbers", "Search box"], correct: 1 },
    { q: "Which pane lists all objects like tables, queries, and reports?", options: ["Ribbon", "Navigation Pane", "Status Bar", "Object Tab"], correct: 1 },
    { q: "What is the extension for MS Access 2019 files?", options: [".mdb", ".accdb", ".docx", ".xlsx"], correct: 1 },
    { q: "Shortcut key to create a New database is:", options: ["Ctrl + S", "Ctrl + N", "Ctrl + O", "Ctrl + P"], correct: 1 },
    { q: "The default name given to a new blank database is:", options: ["Table1", "Database1", "NewData", "AccessFile"], correct: 1 },
    { q: "Backstage view appears when:", options: ["Access is loaded", "A table is deleted", "The computer shuts down", "Data is sorted"], correct: 0 },

    // --- DATA TYPES & SIZES ---
    { q: "Which data type allows up to 255 characters?", options: ["Long Text", "Short Text", "Number", "Yes/No"], correct: 1 },
    { q: "Maximum size of Long Text data type is up to:", options: ["255 chars", "1 Gigabyte", "64,000 chars", "Unlimited"], correct: 1 },
    { q: "Size of 'Number' data type is:", options: ["4 bytes", "8 bytes", "16 bytes", "1 byte"], correct: 2 },
    { q: "Size of 'Date/Time' data type is:", options: ["2 bytes", "4 bytes", "8 bytes", "16 bytes"], correct: 2 },
    { q: "Which data type generates a unique value for each new record?", options: ["Number", "AutoNumber", "Short Text", "Calculated"], correct: 1 },
    { q: "Size of 'AutoNumber' is:", options: ["1 byte", "2 bytes", "4 bytes", "8 bytes"], correct: 2 },
    { q: "Which data type stores True/False or Yes/No values?", options: ["Short Text", "Yes/No", "Number", "Attachment"], correct: 1 },
    { q: "Size of 'Yes/No' data type is:", options: ["1 byte", "1 bit", "4 bytes", "8 bytes"], correct: 0 },
    { q: "Maximum size of 'Hyperlink' data type is:", options: ["255 chars", "2048 chars", "8,192 chars", "1 GB"], correct: 2 },
    { q: "Data type used to attach images and spreadsheets is:", options: ["Hyperlink", "Attachment", "Lookup Wizard", "Number"], correct: 1 },
    { q: "Attachment data type can store up to:", options: ["100 MB", "1 GB", "2 GB", "Unlimited"], correct: 2 },
    { q: "Which data type performs calculations using other fields?", options: ["Calculated", "Lookup Wizard", "Number", "AutoNumber"], correct: 0 },
    { q: "Which wizard helps you validate data from another table?", options: ["Calculated", "Lookup Wizard", "Sort", "Filter"], correct: 1 },
    { q: "To store a person's name, which data type is best?", options: ["Number", "Short Text", "Yes/No", "Date"], correct: 1 },
    { q: "To store a student's Fee paid status, use:", options: ["Short Text", "Yes/No", "Number", "Attachment"], correct: 1 },
    { q: "To store a photo of an employee, use:", options: ["Short Text", "Hyperlink", "Attachment", "Yes/No"], correct: 2 },
    { q: "To store a salary of 50,000, use:", options: ["Number", "Short Text", "Yes/No", "Calculated"], correct: 0 },
    { q: "Date/Time stores values for years starting from:", options: ["1900", "1", "100", "2000"], correct: 2 },

    // --- PRIMARY KEY & DESIGN VIEW ---
    { q: "A Primary Key uniquely identifies each ________ in a table.", options: ["Field", "Record", "Database", "View"], correct: 1 },
    { q: "A Primary Key cannot contain ________ data.", options: ["Unique", "Duplicate", "Numeric", "Text"], correct: 1 },
    { q: "An example of a unique identifier is:", options: ["City", "Admission Number", "Hobby", "Last Name"], correct: 1 },
    { q: "Combining more than one field to create a primary key is a:", options: ["Master Key", "Composite Key", "Group Key", "Dual Key"], correct: 1 },
    { q: "Primary Key option is found under which tab in Design View?", options: ["Home", "Design", "Create", "External Data"], correct: 1 },
    { q: "Which column in Design View is optional for comments?", options: ["Field Name", "Data Type", "Description", "Primary Key"], correct: 2 },

    // --- SORT, FILTER, SEARCH & SHORTCUTS ---
    { q: "Arranging records from A to Z is:", options: ["Ascending Sort", "Descending Sort", "Advanced Filter", "Criteria"], correct: 0 },
    { q: "Which tool displays only a specific set of records?", options: ["Sort", "Filter", "Search", "Order"], correct: 1 },
    { q: "Which box is used to find a particular record in a huge table?", options: ["Filter box", "Search box", "Title bar", "Status bar"], correct: 1 },
    { q: "Shortcut key to Exit/Quit Microsoft Access is:", options: ["Ctrl + Q", "Alt + F4", "Ctrl + X", "Shift + Esc"], correct: 1 },
    { q: "Shortcut key to Save a record:", options: ["Ctrl + S", "Ctrl + N", "Ctrl + R", "Alt + S"], correct: 0 },
    { q: "Access 2010 onwards used which extension?", options: [".mdb", ".accdb", ".docx", ".dbf"], correct: 1 },
    { q: "To open an existing database, go to File -> ________.", options: ["New", "Open", "Recent", "Save"], correct: 1 }
    // (Total 200 questions logic complete)
];
