const chapter5Data = [
    // --- DATABASE BASICS & DBMS ---
    { q: "An organized collection of data is called a:", options: ["Folder", "Database", "File", "Cabinet"], correct: 1 },
    { q: "What does DBMS allow you to do with data?", options: ["Store and retrieve", "Modify and delete", "Manage information", "All of these"], correct: 3 },
    { q: "Full form of DBMS is:", options: ["Data Base Management System", "Database Manual System", "Digital Base System", "None"], correct: 0 },
    { q: "Who built the Analytical Machine, the first programmable computer?", options: ["Charles Babbage", "Bill Gates", "Alan Turing", "Steve Jobs"], correct: 0 },
    { q: "A telephone address book is an example of a:", options: ["Spreadsheet", "Database", "Text file", "Application"], correct: 1 },
    { q: "Banks use databases to keep track of:", options: ["Customer balances", "Account transactions", "Deposits", "All of these"], correct: 3 },
    { q: "Manual databases on paper are prone to:", options: ["High speed", "Errors", "Security", "Flexibility"], correct: 1 },
    { q: "Databases allow multiple users to access data at:", options: ["Different times", "Once (simultaneously)", "Only on weekends", "Never"], correct: 1 },
    { q: "Plain text databases with fixed structures are called:", options: ["Relational", "Flat-file", "Multi-dimensional", "Network"], correct: 1 },
    { q: "Which database type uses related tables of information?", options: ["Flat-file", "Relational", "Linear", "Simple"], correct: 1 },
    { q: "What is the primary form of data storage in a database?", options: ["Queries", "Tables", "Forms", "Reports"], correct: 1 },
    { q: "The intersection of a row and a column is a:", options: ["Record", "Field", "Cell", "Value"], correct: 2 },
    { q: "Columns in a table are also known as:", options: ["Records", "Tuples", "Fields (Attributes)", "Sheets"], correct: 2 },
    { q: "Rows in a table are also known as:", options: ["Fields", "Records (Tuples)", "Cells", "Attributes"], correct: 1 },
    { q: "A request for specific information from a table is a:", options: ["Report", "Form", "Query", "Link"], correct: 2 },
    { q: "The condition specified in a query is called:", options: ["Filter", "Criteria", "Selection", "Logic"], correct: 1 },
    { q: "Which component provides a user-friendly interface for data entry?", options: ["Table", "Form", "Query", "Report"], correct: 1 },
    { q: "The formatted and printable result of a database is a:", options: ["Query", "Form", "Report", "Record"], correct: 2 },
    { q: "MS Access is a part of which software suite?", options: ["Adobe", "Microsoft Office", "Google", "Linux"], correct: 1 },
    { q: "Access uses which database engine?", options: ["Oracle", "Microsoft Jet Database Engine", "SQL Server", "MySQL"], correct: 1 },
    { q: "Which view is used to define the structure of a table?", options: ["Datasheet View", "Design View", "Print View", "SQL View"], correct: 1 },
    { q: "Which view is used for entering data into the table?", options: ["Design View", "Datasheet View", "Layout View", "Form View"], correct: 1 },
    { q: "Title bar in Access displays the name of the:", options: ["User", "Application and Database", "Computer", "ISP"], correct: 1 },
    { q: "Where can you find the Save, Undo, and Redo buttons?", options: ["Ribbon", "Status Bar", "Quick Access Toolbar", "Navigation Pane"], correct: 2 },
    { q: "The 'Ribbon' in Access contains:", options: ["File names", "Tabs and groups of commands", "Current record numbers", "Search box"], correct: 1 },
    { q: "Which pane lists all objects like tables, queries, and reports?", options: ["Ribbon", "Navigation Pane", "Status Bar", "Object Tab"], correct: 1 },
    { q: "What is the extension for MS Access 2019 files?", options: [".mdb", ".accdb", ".docx", ".xlsx"], correct: 1 },
    { q: "Shortcut key to create a New database is:", options: ["Ctrl + S", "Ctrl + N", "Ctrl + O", "Ctrl + P"], correct: 1 },
    { q: "The default name given to a new blank database is:", options: ["Table1", "Database1", "NewData", "AccessFile"], correct: 1 },
    { q: "Backstage view appears when:", options: ["Access is loaded", "A table is deleted", "The computer shuts down", "Data is sorted"], correct: 0 },

    // --- DATA TYPES & SIZES ---
    { q: "Which data type allows up to 255 characters?", options: ["Long Text", "Short Text", "Number", "Yes/No"], correct: 1 },
    { q: "Maximum size of Long Text data type is up to:", options: ["255 chars", "1 Gigabyte", "64,000 chars", "Unlimited"], correct: 1 },
    { q: "Size of 'Number' data type is:", options: ["4 bytes", "8 bytes", "16 bytes", "1 byte"], correct: 2 },
    { q: "Size of 'Date/Time' data type is:", options: ["2 bytes", "4 bytes", "8 bytes", "16 bytes"], correct: 2 },
    { q: "Which data type generates a unique value for each new record?", options: ["Number", "AutoNumber", "Short Text", "Calculated"], correct: 1 },
    { q: "Size of 'AutoNumber' is:", options: ["1 byte", "2 bytes", "4 bytes", "8 bytes"], correct: 2 },
    { q: "Which data type stores True/False or Yes/No values?", options: ["Short Text", "Yes/No", "Number", "Attachment"], correct: 1 },
    { q: "Size of 'Yes/No' data type is:", options: ["1 byte", "1 bit", "4 bytes", "8 bytes"], correct: 0 },
    { q: "Maximum size of 'Hyperlink' data type is:", options: ["255 chars", "2048 chars", "8,192 chars", "1 GB"], correct: 2 },
    { q: "Data type used to attach images and spreadsheets is:", options: ["Hyperlink", "Attachment", "Lookup Wizard", "Number"], correct: 1 },
    { q: "Attachment data type can store up to:", options: ["100 MB", "1 GB", "2 GB", "Unlimited"], correct: 2 },
    { q: "Which data type performs calculations using other fields?", options: ["Calculated", "Lookup Wizard", "Number", "AutoNumber"], correct: 0 },
    { q: "Which wizard helps you validate data from another table?", options: ["Calculated", "Lookup Wizard", "Sort", "Filter"], correct: 1 },
    { q: "To store a person's name, which data type is best?", options: ["Number", "Short Text", "Yes/No", "Date"], correct: 1 },
    { q: "To store a student's Fee paid status, use:", options: ["Short Text", "Yes/No", "Number", "Attachment"], correct: 1 },
    { q: "To store a photo of an employee, use:", options: ["Short Text", "Hyperlink", "Attachment", "Yes/No"], correct: 2 },
    { q: "To store a salary of 50,000, use:", options: ["Number", "Short Text", "Yes/No", "Calculated"], correct: 0 },
    { q: "Date/Time stores values for years starting from:", options: ["1900", "1", "100", "2000"], correct: 2 },

    // --- PRIMARY KEY & DESIGN VIEW ---
    { q: "A Primary Key uniquely identifies each ________ in a table.", options: ["Field", "Record", "Database", "View"], correct: 1 },
    { q: "A Primary Key cannot contain ________ data.", options: ["Unique", "Duplicate", "Numeric", "Text"], correct: 1 },
    { q: "An example of a unique identifier is:", options: ["City", "Admission Number", "Hobby", "Last Name"], correct: 1 },
    { q: "Combining more than one field to create a primary key is a:", options: ["Master Key", "Composite Key", "Group Key", "Dual Key"], correct: 1 },
    { q: "Primary Key option is found under which tab in Design View?", options: ["Home", "Design", "Create", "External Data"], correct: 1 },
    { q: "Which column in Design View is optional for comments?", options: ["Field Name", "Data Type", "Description", "Primary Key"], correct: 2 },

    // --- SORT, FILTER, SEARCH & SHORTCUTS ---
    { q: "Arranging records from A to Z is:", options: ["Ascending Sort", "Descending Sort", "Advanced Filter", "Criteria"], correct: 0 },
    { q: "Which tool displays only a specific set of records?", options: ["Sort", "Filter", "Search", "Order"], correct: 1 },
    { q: "Which box is used to find a particular record in a huge table?", options: ["Filter box", "Search box", "Title bar", "Status bar"], correct: 1 },
    { q: "Shortcut key to Exit/Quit Microsoft Access is:", options: ["Ctrl + Q", "Alt + F4", "Ctrl + X", "Shift + Esc"], correct: 1 },
    { q: "Shortcut key to Save a record:", options: ["Ctrl + S", "Ctrl + N", "Ctrl + R", "Alt + S"], correct: 0 },
    { q: "Access 2010 onwards used which extension?", options: [".mdb", ".accdb", ".docx", ".dbf"], correct: 1 },
    { q: "To open an existing database, go to File -> ________.", options: ["New", "Open", "Recent", "Save"], correct: 1 },
    { q: "Which key is known as a unique identifier of a database table?", options: ["Foreign Key", "Primary Key", "Master Key", "Enter Key"], correct: 1 },
    { q: "A primary key can neither have duplicated data nor can it be ________.", options: ["Numbered", "Left blank", "Deleted", "Formatted"], correct: 1 },
    { q: "Which of the following is an example of a unique identifier?", options: ["Student's name", "Aadhaar Card number", "City name", "Hobby"], correct: 1 },
    { q: "To set a primary key, in which view should you open the table?", options: ["Datasheet View", "Design View", "Print View", "Layout View"], correct: 1 },
    { q: "In Design View, the Primary Key option is found in which group?", options: ["Records group", "Tools group", "Views group", "Tables group"], correct: 1 },
    { q: "When more than one fields are combined to uniquely identify a record, it is called:", options: ["Multiple Key", "Composite Key", "Group Key", "Double Key"], correct: 1 },
    { q: "By default, which data type appears when you enter a new field name in Design View?", options: ["Number", "Short Text", "Yes/No", "Date"], correct: 1 },
    { q: "Which column in Design View is optional and used for specifying comments for future reference?", options: ["Field Name", "Data Type", "Description", "Field Properties"], correct: 2 },

    // --- Section 9: Entering and Modifying Data ---
    { q: "Data can be inserted or entered into a table only in which view?", options: ["Design View", "Datasheet View", "Backstage View", "SQL View"], correct: 1 },
    { q: "In Datasheet View, which symbol marks the row where your new data will be entered?", options: ["Plus (+)", "Asterisk (*)", "Arrow (>)", "Dollar ($)"], correct: 1 },
    { q: "Which key allows you to move to the next field while entering data?", options: ["Esc", "Tab or Enter", "Shift", "Space"], correct: 1 },
    { q: "Where can you observe the current record number in MS Access?", options: ["Title Bar", "Record navigation bar", "Ribbon", "Status Bar"], correct: 1 },
    { q: "To add a new record, you can click the 'New' option in the Records group of which tab?", options: ["Insert", "Home", "Create", "Design"], correct: 1 },
    { q: "After modifying or editing a record, the edited record is saved ________.", options: ["Manually", "Automatically", "Never", "In a new file"], correct: 1 },

    // --- Section 10: Managing Fields (Add, Delete, Hide) ---
    { q: "To add a field by right-clicking on a column header, you should be in:", options: ["Datasheet View", "Design View", "Form View", "Backstage View"], correct: 0 },
    { q: "When you insert a new field in Datasheet View, what is its default temporary name?", options: ["FieldN", "NewColumn", "Column1", "AccessField"], correct: 0 },
    { q: "To delete a field, you can right-click the field name and select ________ from the context menu.", options: ["Remove", "Delete Field", "Clear Column", "Cut"], correct: 1 },
    { q: "What appears on the screen before a field is actually deleted in Access?", options: ["A sound", "A warning message", "A blue screen", "The computer restarts"], correct: 1 },
    { q: "To move a field, you must click on the field name and drag the ________ that appears.", options: ["Red line", "Dark black line", "Dotted line", "White arrow"], correct: 1 },
    { q: "Which option in the context menu allows you to make a field invisible without deleting it?", options: ["Delete", "Hide", "Freeze", "Unbind"], correct: 1 },
    { q: "To bring back a hidden field, you must select which option?", options: ["Show all", "Unhide Fields", "Reveal", "Insert"], correct: 1 },

    // --- Section 11: Sorting, Filtering & Searching ---
    { q: "Arranging data in ascending or descending order is called:", options: ["Filtering", "Sorting", "Searching", "Grouping"], correct: 1 },
    { q: "Which sorting order arranges text from A to Z?", options: ["Descending", "Ascending", "Random", "Logical"], correct: 1 },
    { q: "Which option allows you to display only a specific set of records based on a condition?", options: ["Sort", "Filter", "Search", "Order"], correct: 1 },
    { q: "The 'Greater Than' or 'Greater Than or Equal To' options are found in which filter type?", options: ["Text Filters", "Number Filters", "Color Filters", "Auto Filters"], correct: 1 },
    { q: "Which feature is used when you have to narrow down records based on complex criteria?", options: ["Basic Filter", "Advanced Filter", "Quick Search", "Sort Z to A"], correct: 1 },
    { q: "What is the file format extension used by MS Access 2010 onwards?", options: [".mdb", ".accdb", ".docx", ".xlsx"], correct: 1 },
    { q: "Access 2007 introduced which file extension for databases?", options: [".db", ".accdb", ".sql", ".mdb"], correct: 1 },
    { q: "To find a specific word or date in a huge table, which box on the navigation bar is used?", options: ["Go To", "Search box", "Filter box", "Command box"], correct: 1 },

    // --- Section 12: Exiting & Shortcuts ---
    { q: "To close the current database without exiting the application, you click File then ________.", options: ["Exit", "Close", "Save", "New"], correct: 1 },
    { q: "Which shortcut key combination is used to quit Microsoft Access?", options: ["Alt + F4", "Ctrl + Q", "Alt + C", "Ctrl + X"], correct: 0 }
];
