const gkquizData = [
    // --- Chapter 1: Unique Animals ---
    { q: "Which extremely rare wild ox from Asia was unknown until 1937?", options: ["Gaur", "Kouprey", "Wild Water Buffalo", "Yak"], correct: 1 },
    { q: "Cave paintings of the Kouprey were found in which country?", options: ["Vietnam", "Thailand", "Cambodia", "Laos"], correct: 2 },
    { q: "Which animal uses its tail as a 'fifth limb' to swing between branches?", options: ["Spider Monkey", "Chimpanzee", "Lemur", "Sloth"], correct: 0 },
    { q: "Where do Spider Monkeys normally live?", options: ["Forest floor", "River banks", "Uppermost canopies of rainforests", "Grasslands"], correct: 2 },
    { q: "Which bird derives its name from the crest of long quill-like feathers on its head?", options: ["Secretary bird", "Peacock", "Eagle", "Ostrich"], correct: 0 },
    { q: "Where does the Secretary bird primarily hunt its prey?", options: ["In the air", "In thick forests", "On foot in open grasslands", "Underground"], correct: 2 },
    { q: "The greasy substance secreted by the Civet's scent gland is used in the manufacturing of:", options: ["Soaps", "Perfumes", "Medicines", "Cooking oil"], correct: 1 },
    { q: "The cat-like mammal Civet is a native of which continents?", options: ["Australia", "Europe", "Africa and Asia", "North America"], correct: 2 },
    { q: "Which African antelope is a desert dweller found in the Sahara desert?", options: ["Impala", "Addax", "Gazelle", "Eland"], correct: 1 },
    { q: "The Addax antelope has wide-spreading hooves that are ideal for:", options: ["Climbing trees", "Swimming", "Walking on soft sand", "Running on rocks"], correct: 2 },
    { q: "Which odd-looking bird builds its nest in a burrow?", options: ["Puffin", "Woodpecker", "Kingfisher", "Swallow"], correct: 0 },
    { q: "A Puffin's beak is dull yellow at the base and which color at the end?", options: ["Blue", "Green", "Vermilion", "Black"], correct: 2 },
    { q: "What color is the middle part of a Puffin's triangular hooked beak?", options: ["Red", "Blue", "Yellow", "Orange"], correct: 1 },

    // --- Chapter 2: Laughter Therapy ---
    { q: "Laughter reduces the risk of heart attack by improving the functioning of:", options: ["Lungs", "Blood vessels", "Kidneys", "Liver"], correct: 1 },
    { q: "Laughter helps the body release feel-good hormones called:", options: ["Adrenaline", "Insulin", "Endorphins", "Thyroxine"], correct: 2 },
    { q: "Laughter increases the production of ________ to fight diseases like common cold.", options: ["Red blood cells", "Antibodies", "Platelets", "Hormones"], correct: 1 },
    { q: "Which stress hormone is reduced by laughter?", options: ["Endorphins", "Adrenaline", "Serotonin", "Dopamine"], correct: 1 },
    { q: "One of the social benefits of laughter is that it keeps people:", options: ["Further apart", "Closer to each other", "Quiet", "Sleepy"], correct: 1 },

    // --- Chapter 3: Amazing Places Around The World ---
    { q: "The Great Blue Hole, a massive submarine sinkhole, is located off the coast of:", options: ["Mexico", "Belize", "Brazil", "Australia"], correct: 1 },
    { q: "Where can you find around 1,268 cone-shaped hills known as Chocolate Hills?", options: ["Philippines", "Indonesia", "India", "China"], correct: 0 },
    { q: "The Chocolate Hills in Bohol, Philippines are spread over an area of more than:", options: ["10 sq km", "50 sq km", "100 sq km", "500 sq km"], correct: 1 },
    { q: "The Wave, a red-rock stunner made of 190 million-year-old sand dunes, is on the border of:", options: ["California and Nevada", "Arizona and Utah", "Texas and New Mexico", "Colorado and Wyoming"], correct: 1 },
    { q: "The 'Richat Structure' in the Sahara Desert is also known as the:", options: ["Heart of Africa", "Eye of the Sahara", "Sahara Ring", "Desert Vortex"], correct: 1 },
    { q: "Cano Cristales, known as the 'Liquid Rainbow', is located in which country?", options: ["Peru", "Colombia", "Chile", "Argentina"], correct: 1 },
    { q: "The vibrant colors in the Cano Cristales river are produced by:", options: ["Pollution", "Algae", "Special rocks", "Chemicals"], correct: 1 },
    { q: "Pamukkale, known as 'Cotton Castle', is located in which country?", options: ["Greece", "Turkey", "Egypt", "Italy"], correct: 1 },
    { q: "The whiteness of Pamukkale is caused by deposits of:", options: ["Salt", "Sugar", "Calcium carbonate", "White sand"], correct: 2 },

    // --- Chapter 4: Endangered Trees ---
    { q: "The endangered 'Bois Dentelle Tree' is found only in:", options: ["Madagascar", "Mauritius", "Sri Lanka", "Maldives"], correct: 1 },
    { q: "Only about 300 trees of the 'Loulu Tree' are left in the:", options: ["Hawaiian Islands", "Caribbean Islands", "Fiji", "Tahiti"], correct: 0 },
    { q: "The 'St Helena Gumwood Tree' grows with a crooked trunk and many branches on:", options: ["Easter Island", "St Helena Island", "Galapagos", "Iceland"], correct: 1 },
    { q: "The 'Dragon Tree', known for its prickly leaves, is found on which islands?", options: ["Canary Islands", "Madeira", "Cape Verde Islands", "All of these"], correct: 3 },
    { q: "In which country is 'Hinton’s Oak Tree' found?", options: ["Canada", "USA", "Mexico", "Brazil"], correct: 2 },
    { q: "The African Baobab Tree can grow up to 98 feet in height and how many feet in diameter?", options: ["10 feet", "25 feet", "36 feet", "50 feet"], correct: 2 },

    // --- Chapter 5: Spacewalk ---
    { q: "What is the technical term for a Spacewalk?", options: ["Space Journey", "Extra-vehicular Activity (EVA)", "Astro-walk", "Orbit Exit"], correct: 1 },
    { q: "Who was the first human to walk in space on March 18, 1965?", options: ["Neil Armstrong", "Yuri Gagarin", "Alexei Leonov", "Buzz Aldrin"], correct: 2 },
    { q: "Alexei Leonov performed the first spacewalk from which spacecraft?", options: ["Apollo 11", "Voshkod II", "Salyut 7", "Sputnik"], correct: 1 },
    { q: "Who was the first woman to perform a spacewalk?", options: ["Valentina Tereshkova", "Sally Ride", "Svetlana Savitskaya", "Susan Helms"], correct: 2 },
    { q: "Which American astronaut performed the longest spacewalk of 8 hours and 56 minutes?", options: ["Sunita Williams", "Susan Helms", "Peggy Whitson", "Jessica Meir"], correct: 1 },
    { q: "Who performed the first in-flight repair of the Space Shuttle on August 3, 2005?", options: ["Steve Robinson", "Scott Kelly", "Chris Hadfield", "John Glenn"], correct: 0 },
    { q: "Who holds the record for most spacewalks (16) and longest duration of EVA?", options: ["Anatoly Solovyev", "Gennady Padalka", "Alexei Leonov", "Zhai Zhigang"], correct: 0 },
    { q: "Who was the first Chinese astronaut to spend 20 minutes walking in space?", options: ["Yang Liwei", "Zhai Zhigang", "Liu Yang", "Fei Junlong"], correct: 1 },
    { q: "What is the biggest danger during spacewalks apart from floating away?", options: ["Sunburn", "Space debris collision", "Alien encounter", "Lack of stars"], correct: 1 },

    // --- Chapter 6: Forts Of India ---
    { q: "Which fort is one of the largest desert forts in the world, located in Jaisalmer?", options: ["Agra Fort", "Jaisalmer Fort", "Amber Fort", "Red Fort"], correct: 1 },
    { q: "Jaisalmer Fort stands proudly amidst the golden stretches of Thar Desert on which hill?", options: ["Aravalli Hill", "Trikuta Hill", "Chitrakoot Hill", "Nilgiri Hill"], correct: 1 },
    { q: "Jaisalmer Fort is also known as 'Golden Fort' because of its walls made of:", options: ["Gold bricks", "Yellow limestone", "Yellow sandstone", "Polished marble"], correct: 2 },
    { q: "Who built the Jaisalmer Fort in 1156 CE?", options: ["Rao Jodha", "Raja Rawal Jaisal", "Akbar", "Shah Jahan"], correct: 1 },
    { q: "Which marble palace inside the Agra Fort is famous for paintings on marble?", options: ["Sheesh Mahal", "Moti Mahal", "Khas Mahal", "Phool Mahal"], correct: 2 },
    { q: "Which Mughal Emperor built the Agra Fort with redstone?", options: ["Babur", "Humayun", "Akbar", "Shah Jahan"], correct: 2 },
    { q: "The Red Fort in Delhi was designated as a UNESCO World Heritage Site in which year?", options: ["2000", "2005", "2007", "2010"], correct: 2 },
    { q: "In which year was the Red Fort built by Shah Jahan?", options: ["1556 CE", "1648 CE", "1459 CE", "1592 CE"], correct: 1 },
    { q: "Mehrangarh Fort is located in which city of Rajasthan?", options: ["Jaipur", "Udaipur", "Jodhpur", "Bikaner"], correct: 2 },
    { q: "The foundation of Mehrangarh Fort was laid in 1459 by:", options: ["Rao Jodha", "Raja Man Singh", "Rao Jaisal", "Akbar"], correct: 0 },
    { q: "Which fort is situated on the banks of River Yamuna where Humayun built his capital Dina-Panah?", options: ["Red Fort", "Purana Qila", "Agra Fort", "Amber Fort"], correct: 1 },
    { q: "Who was the founder of the Suri Dynasty that named Purana Qila as 'Shergarh'?", options: ["Humayun", "Sher Shah Suri", "Akbar", "Babur"], correct: 1 },
    { q: "Amber Fort is located how many kilometers from Jaipur, Rajasthan?", options: ["5 km", "11 km", "20 km", "50 km"], correct: 1 },
    { q: "Amber Fort was built during the reign of which ruler?", options: ["Raja Man Singh", "Raja Jaisal", "Shah Jahan", "Humayun"], correct: 0 },
    { q: "The 'Hall of Mirrors' is a splendid sight found in which fort?", options: ["Mehrangarh Fort", "Amber Fort", "Jaisalmer Fort", "Purana Qila"], correct: 1 },

    // --- Chapter 7: Women In Science ---
    { q: "Who was India’s first woman scientist to spend more than a year in Antarctica?", options: ["Aditi Pant", "Mangala Mani", "Ritu Karidhal", "Anna Mani"], correct: 1 },
    { q: "Mangala Mani was the only woman in a team of how many scientists sent to Antarctica?", options: ["10", "23", "50", "100"], correct: 1 },
    { q: "Which 12-year-old American inventor created 'Tethys' to measure lead in drinking water?", options: ["Gitanjali Rao", "Jennifer Doudna", "Susan Helms", "Cynthia Rosenzweig"], correct: 0 },
    { q: "Gitanjali Rao was featured as 'Kid of the Year' on the cover of which magazine?", options: ["National Geographic", "Forbes", "TIME", "Discovery"], correct: 2 },
    { q: "Which scientist forecasted the effects of Hurricane Sandy 12 years before the disaster?", options: ["Jennifer Doudna", "Cynthia Rosenzweig", "Ritu Karidhal", "Mangala Mani"], correct: 1 },
    { q: "Cynthia Rosenzweig received which prestigious prize in 2022?", options: ["Nobel Prize", "World Food Prize", "Fields Medal", "Bharat Ratna"], correct: 1 },
    { q: "Who is known as the 'Rocket Woman of India'?", options: ["Kalpana Chawla", "Sunita Williams", "Ritu Karidhal", "Tessy Thomas"], correct: 2 },
    { q: "Ritu Karidhal played an important role in the development of which mission?", options: ["Chandrayaan-2", "Mars Orbiter Mission (Mangalyaan)", "Aditya-L1", "Gaganyaan"], correct: 1 },
    { q: "Which Nobel Prize winner discovered that immunity-controlling bacteria could change DNA?", options: ["Marie Curie", "Jennifer Doudna", "Gitanjali Rao", "Anna Mani"], correct: 1 },
    { q: "Which woman scientist worked with Nobel Laureate C.V. Raman?", options: ["Anna Mani", "Mangala Mani", "Ritu Karidhal", "Janaki Ammal"], correct: 0 },

    // --- Chapter 8: World’s Most Amazing Natural Phenomena ---
    { q: "At Skagen City in Denmark, which two seas meet but cannot merge due to different densities?", options: ["Red Sea and Med Sea", "Baltic and North Seas", "Arabian and Black Seas", "Dead Sea and Caspian Sea"], correct: 1 },
    { q: "The phenomenon where heavy rocks move across a dry lake bed in Death Valley is called:", options: ["Flying Rocks", "Moving Stones", "Sliding Boulders", "Walking Pebbles"], correct: 1 },
    { q: "Moving Stones are found in which National Park?", options: ["Yellowstone", "Death Valley National Park", "Grand Canyon", "Yosemite"], correct: 1 },
    { q: "Which phenomenon occurs in cold places where slow-moving river water forms a circular shape?", options: ["Ice Circles", "Snow Rings", "Frozen Whirls", "Frost Plates"], correct: 0 },
    { q: "A 'Fire Whirl' is a rare phenomenon that creates a:", options: ["Fire Cloud", "Fire Storm", "Tornado-like effect of fire", "Burning Rain"], correct: 2 },
    { q: "Where are 'Penitentes' (tall thin blades of hardened snow) formed?", options: ["Himalayas", "Andes Mountains", "Alps", "Rockies"], correct: 1 },
    { q: "In which countries are Penitentes commonly found?", options: ["India and China", "Chile and Argentina", "USA and Canada", "Norway and Sweden"], correct: 1 },
    { q: "Red Tides are caused by the rapid growth of:", options: ["Red fish", "Corals", "Algae", "Seaweed"], correct: 2 },

    // --- Chapter 10: The Living Machine ---
    { q: "The smallest bone in the human body measures 2.6-3.4 mm. What is it called?", options: ["Hammer", "Anvil", "Stapes", "Femur"], correct: 2 },
    { q: "The smallest bone in the human body weighs between:", options: ["0.5 to 1 mg", "2 to 4.3 mg", "10 to 15 mg", "1 to 2 mg"], correct: 1 },
    { q: "Where is the Stapes bone located?", options: ["Inner ear", "Middle ear", "Outer ear", "Nose"], correct: 1 },
    { q: "What is the smallest muscle in the human body that controls the stapes?", options: ["Sartorius", "Stapedius", "Gluteus", "Stirrup"], correct: 1 },
    { q: "What is the largest artery in the human body, measuring about 3 cm in diameter?", options: ["Vena Cava", "Aorta", "Pulmonary Artery", "Carotid"], correct: 1 },
    { q: "The largest artery, Aorta, leaves which part of the body?", options: ["Lungs", "Heart", "Liver", "Brain"], correct: 1 },
    { q: "Which is the longest cell in the human body?", options: ["Skin cell", "Muscle cell", "Neuron", "Liver cell"], correct: 2 },
    { q: "Successive generations of which white blood cell contain the memory of previous illnesses?", options: ["Neutrophils", "Lymphocytes", "Monocytes", "Eosinophils"], correct: 1 },
    { q: "Which is the most abundant cell (around 30 billion) in the human body?", options: ["White blood cells", "Red blood cells", "Platelets", "Stem cells"], correct: 1 },
    { q: "Where are red blood cells produced?", options: ["Heart", "Lungs", "Bone marrow", "Liver"], correct: 2 },
    { q: "What is the function of red blood cells?", options: ["Fight infection", "Carry oxygen and carbon dioxide", "Stop bleeding", "Digest food"], correct: 1 },
    { q: "Which is the bulkiest of the 639 named muscles in the human body?", options: ["Thigh muscle", "Buttock muscle (Gluteus Maximus)", "Back muscle", "Chest muscle"], correct: 1 },
    { q: "The most active muscle moves more than 100,000 times a day. Which one is it?", options: ["Heart muscle", "Jaw muscle", "Eye muscle", "Diaphragm"], correct: 2 },
    { q: "Which is the largest sesamoid bone in the body?", options: ["Stapes", "Patella (knee cap)", "Aorta", "Tibia"], correct: 1 },

    // --- Chapter 11: Futuristic World ---
    { q: "Which smart city concept is designed to float on water and generate 100% of its food and energy?", options: ["Eco-City", "Oceanix", "Water-World", "Aqua-City"], correct: 1 },
    { q: "The Oceanix floating city will generate what percentage of its food, energy and water supply?", options: ["50%", "75%", "100%", "90%"], correct: 2 },
    { q: "The Oceanix floating city is designed to accommodate how many residents and visitors?", options: ["10,000", "50,000", "More than 1,00,000", "5,00,000"], correct: 2 },
    { q: "What is the name of the driverless, environment-friendly vehicles run on solar power?", options: ["Personal Rapid Transit", "Auto-Solar Cabs", "Green Transit", "Speed Pods"], correct: 0 },
    { q: "One small Personal Rapid Transit vehicle could cost how much compared to an ordinary car?", options: ["Half", "One-fifth", "One-tenth", "Same cost"], correct: 2 },
    { q: "How many people can a single automated Personal Rapid Transit vehicle carry at a time?", options: ["2 to 4", "4 to 6", "6 to 8", "8 to 10"], correct: 1 },
    { q: "What is the name of the technology that transforms skyscrapers into vertical farming towers?", options: ["Sky-Farms", "Farm Scrapers", "Green Towers", "Eco-Scrapers"], correct: 1 },
    { q: "Farm Scrapers are designed to produce enough food to feed around how many people?", options: ["10,000", "25,000", "40,000", "1,00,000"], correct: 2 },
    { q: "Vertical farms in Farm Scrapers can absorb how much Carbon Dioxide (Co2) in a year?", options: ["5,000 kg", "10,000 kg", "20,000 kg", "50,000 kg"], correct: 2 },
    { q: "In Windowless Planes, high-definition display panels will project what kind of view?", options: ["180 degree", "270 degree", "360 degree", "Front view only"], correct: 2 },
    { q: "A solar-powered house concept roof is composed of what to provide energy?", options: ["Glass tiles", "Solar cells", "Plastic sheets", "Iron plates"], correct: 1 },
    { q: "The sustainable solar-powered house concept uses 95% of which renewable construction material?", options: ["Plastic", "Steel", "Wood", "Glass"], correct: 2 },
    { q: "Which underwater city concept features a 500-metre spherical city that floats deep sea?", options: ["Sub-City", "Ocean Spiral City", "Deep-Blue City", "Dolphin City"], correct: 1 },
    { q: "Which 2002 movie predicted technologies like multi-touch interfaces and retina scanners?", options: ["Inception", "Minority Report", "Interstellar", "Avatar"], correct: 1 }
];
